### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by GrouchyGaijin** [sharat87/ti#22]
Sorry to be so slow, but how exactly can I read my json file to generate beautiful html reports?
I am on Ubuntu 14.04

**Comment by sharat87** [comment]
Hey, sorry for not responding sooner. You're not slow, I am. The HTML reports suggestion in the README is just an idea. I did something like that a few years ago but nothing that I shared with the project. As all the information you need is in the JSON file, such a report is certainly possible to generate.

Thanks.
