### ISSUE TITLE
Taking over ti development

### ISSUE THREAD

**Issue by tbekolay** [sharat87/ti#27]
Hi @sharat87! Thanks for `ti`, it's a nice utility that scratches an important itch.

You mentioned in #25 that you don't have much time for this project. In my fork, I've done the work necessary to make `ti` pip-installable (see #26). Would it be okay for me to publish my fork on PyPI, making `ti` pip-installable? If so, would you also consider adding something to the README to note that you are no longer maintaining the project, and point to my fork? I'd be happy to deal with all of the PRs made on this repo on my fork.

**Comment by sharat87** [comment]
Sure, go ahead. I'll update the README.

**Comment by tbekolay** [comment]
Thank you!
